nodeLinker: node-modules

plugins:
  - checksum: f9518b31fefd1fba7311daef824559d22aaad4407bd65b3323e8ed862d41e18b8060edd128f32975fee6463665d0032f752799fbc137e0e5333b8e868c4f17a4
    path: .yarn/plugins/@yarnpkg/plugin-dotenv-extended.cjs
    spec: "https://github.com/SmineDDF/yarn-plugin-dotenv-extended/releases/download/3.0.1/plugin-dotenv-extended.js"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
